apiVersion: apps/v1
kind: Deploymnet
metadata:
  name: auth-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: auth-mongo
  template:
    metadata:
      labels:
        app: auth-mongo
    spec:
      containers:
        - name: auth-mongo
          image: mongo


---

apiVersion: v1
kind: Service
metadada: 
  name: auth-mongo-srv
spec:
  selector:
    app: auth-mongo
  ports:
    - name: auth-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017